name: build-artifact
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install and build
        run: |
          yarn install &&
          yarn test
      - name: Build packages
        run: |
          yarn add vsce &&
          bash ./scripts/build-vscode-artifact.sh &&
          bash ./scripts/build-npm-package.sh
      - use: actions/upload-artifact@v2
        with:
          name: vscode-extension
          path: |
            artifacts/vscode/*.vsix
            artifacts/vscode/*.list
      - use: actions/upload-artifact@v2
        with:
          name: npm-package
          path: |
            artifacts/npm/*.vsix
            artifacts/npm/*.list
